### ISSUE TITLE
NUMA support issue

### ISSUE THREAD

**Issue by evan10j** [tf4ong/PRT#2]
Hello,

I have been getting the error as below. I wonder if it is related to tensorflow/cuda/ubuntu version compatibility. Could you please give some suggestions on this? Many thanks!

"
2024-04-23 19:47:15.183360: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:968] could not open file to read NUMA node: /sys/bus/pci/devices/0000:03:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-04-23 19:47:15.183433: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
Segmentation fault
"

**Comment by tf4ong** [comment]
Hi, 

Yes, I believe that is the cuda tool box and cudnn conflicting with that specific tensorflow version. We had alot of trouble shooting to do when installing it on different computers. It would require some trouble shooting dependent on your PC. Here is the versions of cuda, cudnn, tensorflow we used:

tensorflow-gpu==2.3.1
cudnn=7.6.5=cuda10.1_0

Because of how many conflicts we were also running into, our group has moved towards using ultralytics yolov8 (https://github.com/ultralytics/ultralytics) for the trainning and detection. Then we used the tracking and RFID matching in this repo. It was easier to install and run the models. I reccommend you give that a try. I can some scripts to do that if you need but we are planning to release a new version of PMT with the ultralytics package in the fall.

**Comment by evan10j** [comment]
Thank you for sharing the information! Looking forward to the new version! It would be amazing if you could please share some scripts if you already have them.

**Comment by tf4ong** [comment]
Yea, no problem. Can you send me an email t4fong@uwaterloo.ca
